# Site
repository:  Gerard-170/Gera117.github.io 
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Gerardo Huerta Robles
title: Electronic Engineer
email: gerardohuerta1705@gmail.com
# email_title: Email (Email title override)
phone: +505 58073860
website: N/A
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: RoblenHuerta
github_username:  Gerard-170
linkedin_username: Gerardo Huerta Robles

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi there!

  My name is Gerardo Huerta Robles, Engineer passionate about making a career in IT, as an electronic engineer I have also worked in technical support / engineering.
    
  <i class="far fa-lightbulb"></i> Ask me about: Networking, Cybersecurity and DataCenter Solutions, I'm also interested on Embedded Systems and ML, DL.
  
  <i class="fas fa-laptop-code"></i> Programming Languages:  <mark>C/C++</mark>, <mark>MATLAB</mark>, <mark>Python</mark>
  
  <i class="fas fa-user-astronaut"></i> Skills: <mark>Linux</mark>, <mark>PenTest</mark>, <mark>Support Engineer</mark>, <mark>Cisco IOS</mark>, <mark>Embedded Systems</mark>
  
  ![alt text](/images/All_v1.PNG "CR")


content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: ULTRANIC
        sub_title: Electronic Security Systems Impelementer Internship
        caption: (August - October 2018)
        link: https://ultranic.online.com.ni/
        quote: >
          Implement solutions on Electronic security systems for end customer.
        description: | # this will include new lines to allow paragraphs
          - Installation of IP Cameras. 
          - Development of Fire protection systems
      - layout: left
        title: VINET TECHNOLOGY ADVISORY
        sub_title: Consulting engineer
        caption: (August 2020 - present)
        link: https://www.vinet.co.cr/
        quote: >
          IT Solutions from Collaboration to Networking and Security solutions
        description: | # this will include new lines to allow paragraphs
          - Support engineer for Servers, Network devices, security endpoints.
          - Designer of IT solutions for End Customer.
          - Postsell's task such as, deploy and configuration of solution.
  - title: Academic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TrazabNic
        link: https://github.com/Gerard-170/TrazabNic
        link_text: TZN
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Gerard-170/TrazabNic
          - title:  Repo page for project
            icon: fas fa-atlas
            url: https://github.com/Gerard-170/TrazabNic/blob/master/2Poster_STFEC_2_2017.pdf
        quote: >
          Short overview of the project
        description: | # this will include new lines to allow paragraphs
          RFID TAG READER implemented for accounting and managing of livestock, with the purpose to help rancher administrate their stock in a better way. This project was presented at FEC winning the first place in its category.</mark> in <mark>FEC – UNI</mark> 
      - layout: left
        title: Structural Health Monitoring System for Highway Bridges
        link: https://github.com/Gerard-170/SHM_FDD
        link_text: SHM
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Gerard-170/SHM_FDD
          - title:  Repo page for project
            icon: fas fa-atlas
            url: 
        quote: >
          Short overview of the project
        description: | # this will include new lines to allow paragraphs
          SHM_FDD is an embedded appliance of Frecuency Domain Decomposition (FDD) for Structural Health Monitoring (SHM) applying Output Only philosophy with an approach on Modal Identification, Modal Shapes and Modal, Assurance Criterion (MAC).</mark> in <mark>TECNO UNI 2021</mark>
  - title: Education
    layout: list
    content:
      - layout: left
        title:  UNI
        sub_title: Electronics engineer
        caption: (2015 - 2019)
        quote: >
          Universidad Nacional de Ingeniería
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title:  ANI
        sub_title: English as a second language.
        caption: (2016 - 2020)
        quote: >
          Universidad Centroamericana
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title:  CCNA Routing and Switching
        sub_title:  Networking concepts, security, architecture, pricing, and support
        caption: (2020 - 2023)
        quote: >
          Cisco.training
        description: | # this will include new lines to allow paragraphs
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I enjoy reading books and listen to melodic music. I'm participating for ONGs as volunteer on social projects one of them on my birthplace we help children with school materials.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
